- hircluster.c
- hircluster.h
- tests/CMakeLists.txt
- tests/ct_connection.c
When a password is configured it will be sent right
after a connection to a Redis instance is setup,
via the AUTH command.
Added API:
redisClusterSetOptionPassword(cc, "password");
> Add support of password authentication (AUTH)

- hircluster.c
- hircluster.h
- tests/CMakeLists.txt
- tests/ct_pipeline.c
Add tests of using pipelining in both async and sync APIs.
Also change name of internal variable to match naming used in hiredis
> Add pipeline tests

- CMakeLists.txt
- CONTRIBUTING.md
* Added a make target for code formatting using `clang-format`
Code will be formatted according to existing rule by running `make format`
This will make sure the `static checker` job in CI accepts changed code.
* Added an initial CONTRIBUTING.md file. To be improved
> Add code formatting target

- .github/workflows/ci.yml
- CMakeLists.txt
- README.md
- hircluster.c
- tests/CMakeLists.txt
- tests/ct_commands.c
- tests/ct_pipeline.c
- tests/test_utils.h
* Correcting 2 iterator leaks, now covered with tests.
Leaks in multi-command handling:
* redisClusterGetReply()
* command_post_fragment()
* Add option to build using sanitizers
* The option is set when generating makefiles, like the other configs:
`cmake -DDOWNLOAD_HIREDIS=ON -DUSE_SANITIZER=leak ..`
* Build and test using sanitizers in CI aswell
> Leak corrections and testing

- hircluster.c
- tests/CMakeLists.txt
- tests/clusterclient.c
- tests/scripts/ask-redirect-test.sh
- tests/scripts/set-get-test.sh
- tests/scripts/simulated-redis.pl
Test cases using a script simultating one or more Redis nodes, with exact expectations on traffic. The PR contains:
* A Perl script simulating a Redis node, given expected traffic events on stdin.
* A C program wrapping the hiredis-cluster library, performing Redis commands from stdin and writing the results on stdout.
* Test cases (shell script):
* A simple SET and GET test case using a simulated Redis node
* An ASK redirection test case using two simulated Redis nodes
* A memory leak in the ASK redirect handling detected and fixed
> Tests using simulated Redis node

- README.md
- adlist.c
- command.c
- dict.c
- hiarray.c
- hiarray.h
- hircluster.c
- hiutil.c
- hiutil.h
- tests/CMakeLists.txt
- tests/ct_out_of_memory_handling.c
- tests/test_utils.h
- win32.h
This PR handles vipshop/hiredis-vip#136 and the vulnerability report regarding handling failing allocations, see https://nvd.nist.gov/vuln/detail/CVE-2020-7105
* Allocation results are now checked before the memory is used.
* This PR also replaces existing allocation/free macros to use the same api as hiredis
Some details:
Hiredis uses its own allocator-functions which by default uses libc.
By using the same design in hiredis-cluster a user can replace the
allocator for both hiredis and hiredis-cluster at the same time.
Own allocator functions can be enabled by the API:
`hiredisAllocFuncs hiredisSetAllocators(hiredisAllocFuncs *ha)`
> Safe allocations

- .github/workflows/ci.yml
action-setup-cmake suddenly lacks information in reponses from github making it unable to get all cmake versions.
This is a temporary change until that issue is corrected.
> Manual installation of cmake in CI (temporary fix)

- .github/workflows/ci.yml
Seems that older compilers are not available on the now latest 20.04
> CI: Use ubuntu-18.04 as runner

- CHANGELOG.md
- Makefile
- README.md
- examples/src/CMakeLists.txt
- examples/src/example.c
- examples/src/example_async.c
- examples/src/example_tls.c
- examples/using_cmake_externalproject/CMakeLists.txt
- examples/using_cmake_externalproject/build.sh
- examples/using_cmake_separate/build.sh
- examples/using_make/build.sh
A simplified Makefile is added as an alternative to the preferred CMake.
This enables users to choose, just like its done in hiredis.
The current benefit of the provided Makefile, both in hiredis and
hiredis-cluster, is that statically linked libraries can be built.
This is not supported by CMake build in the dependency hiredis v1.0.0.
The examples how to build are improved with setup.sh scripts.
These are working examples that can be used a base for user projects.
> Add alternative makefile and improve examples

- CMakeLists.txt
- CONTRIBUTING.md
- README.md
A new build option is added `ENABLE_COVERAGE=ON`:
Compile using build flags that enables the GNU coverage tool `gcov`
to provide test coverage information. This CMake option also enables a new
build target `coverage` to generate a test coverage report using `gcovr`.
Example:
$ cmake -DENABLE_COVERAGE=ON ..
$ make all test coverage
$ xdg-open ./coverage.html
> Add test coverage support in build

- adlist.c
- dict.c
- dict.h
- hircluster.c
- tests/ct_out_of_memory_handling.c
By replacing the usage of iterator get- & release-functions with init-functions
we can stack allocate list and dict iterators to avoid some costly mallocs.
This also simplifies alternative flows and reduces code.
> Cleanup of dict and list iterators

- CHANGELOG.md
- CMakeLists.txt
- Makefile
- README.md
- command.c
- command.h
- dict.c
- dict.h
- hircluster.c
- hircluster.h
- tests/CMakeLists.txt
- tests/clusterclient_all_nodes.c
- tests/ct_out_of_memory_handling.c
- tests/ct_specific_nodes.c
- tests/scripts/dbsize-to-all-nodes-test.sh
- tests/scripts/simulated-redis.pl
- tests/test_utils.h
Introduce new APIs for sending blocked, transaction and async commands to a
given node. This avoids the parsing step done in the legacy API and enables
keyless commands to be sent aswell, like for transactions.
Redirects are not handled when using this API.
```
void *redisClusterCommandToNode(redisClusterContext *cc, cluster_node *node..
int redisClusterAppendCommandToNode(redisClusterContext *cc, cluster_node *node..
int redisClusterAsyncCommandToNode(redisClusterAsyncContext *acc, cluster_node *node..
```
To send commands to all nodes a node iterator is introduced. It is based on the dict iterator to traverse
the existing nodes dict, but with the additional handling of changes in the nodes dict.
When a route refresh is performed nodes might be added or removed, and since the dict is …
> Add API to send commands to a specific node or all nodes

- hircluster.c
- tests/ct_out_of_memory_handling.c
This change will give better error messages during connection problems in the async API.
Detailed error message set in `actx_get_by_node()` will no longer be replaced by a high-level generic message.
Start using `redisClusterReset()` in the OOM testcase to make sure each test has a fresh start without pre-allocated queues and lists.
> Correct error messages during async connection problems

- CHANGELOG.md
- COPYING
- command.c
* Minimum required version of CMake changed to 3.11 (from 3.14)
* Re-added the Makefile for symmetry with hiredis, which also enables
support for statically-linked libraries.
* Improved examples
* Corrected crashes and leaks in OOM scenarios
* New API for sending commands to specific node
* New API for node iteration, can be used for sending commands
to some or all nodes.
> Release 0.6.0

- command.c
- command.h
- tests/CMakeLists.txt
- tests/ct_commands.c
- tests/ct_specific_nodes.c
This adds tests and support for all stream commands.
The following commands are now handled by the regular API (like `redisClusterCommand()`) and are sent to the cluster node that handles the stream:
`XACK`, `XADD`, `XAUTOCLAIM`, `XCLAIM`, `XDEL`, `XGROUP`, `XINFO`, `XLEN`, `XPENDING`, `XRANGE`, `XREVRANGE` and `XTRIM`
The stream commands `XREAD` and `XREADGROUP` currently requires to be sent using the specific node API,
like `redisClusterCommandToNode()`, this due to that the position of the stream key is not in a fixed position.
> Add support for stream commands

- tests/scripts/dbsize-to-all-nodes-test.sh
This test didn't work on my system because `echo` didn't replace `\n` with a newline. Using `printf` works (see https://github.com/koalaman/shellcheck/wiki/SC2028).
> fix dbsize-to-all-nodes-test test

- COPYING
- command.c
- command.h
- hiarray.c
- hiarray.h
- hircluster.c
- hircluster.h
- hiutil.c
- hiutil.h
Reviewed the commit history for both hiredis-cluster and
its ancestor hiredis-vip and added copyright and license
annotations for all sources.
Updated the main COPYING file with all copyright holders
details (using the email address and actual name deep011
list on github) as it was missing a couple of entries.
Resolves https://github.com/Nordix/hiredis-cluster/issues/35
> Ensure copyright notices exist at the head of all sources

- .clang-format
- .github/workflows/ci.yml
* Trigger CI builds on all push and pull requests
The trick to make sure that only one build was triggered did not work in all scenarios.
* Disable ReflowComments in clang-format
clang-format will attempt to re-flow the comments which breaks the copyright comments in many places.
Disabling ReflowComments will make sure clang-format is not reshuffling longer comment lines, like copyright text, ascii-art and more.
> Build fixes

- tests/ct_connection.c
Verifies that multiple clusters can be accessed simultaneously using the regular or the async API.
> Add tests for multi cluster handling

- hircluster.c
- hircluster.h
- tests/ct_specific_nodes.c
This PR adds a new `redisClusterAsyncFormattedCommandToNode()` function, which does the same as `redisClusterAsyncCommandToNode()` except it takes an already formatted command.
> add redisClusterAsyncFormattedCommandToNode() function

- hircluster.c
reply->element is a vector of redisReply pointers
Previously, the size of the redisReply datastructure got allocated for each element of the vector. With this commit only the size of a pointer to a redisReply does get allocated.
In the lines below only the pointer addresses of e.g. `reply->element[i]` are updated, but no data is copied, so I'm 99% confident that this is a correct change. fwiw, all tests still pass.
> fix sizeof argument in call to calloc for reply->element vector

- hircluster.c
After vendoring hiredis-cluster in our main branch (https://github.com/performancecopilot/pcp) we found a few new [Coverity Scan](https://scan.coverity.com) issues, three of them will be fixed with this PR (one dead code and two mem leaks in an error condition).
> code cleanup

- hiutil.c
Networking functions, types and macros like setsockopt,
send, recv, struct linger, SOL_SOCKET and so on do not
build on the BSD platforms if the socket header is not
included (as per man pages like send(2), setsockopt(2),
etc).  Fixed by adding it to hiutil.c which appears to
be the only location we need it.
> Include <sys/socket.h> for builds on the BSD platforms

- .github/workflows/coverity.yml
Coverity Scan has limits on the frequency of build submissions (https://scan.coverity.com/faq#frequency), so I've configured weekly scans for now. If there are less than 4 daily commits to the master branch, we could also run a scan on every commit to the master branch.
Resolves #46
> ci: add coverity scan

- .github/workflows/ci.yml
- examples/src/CMakeLists.txt
- examples/using_cmake_externalproject/CMakeLists.txt
- examples/using_cmake_externalproject/build.sh
- examples/using_cmake_separate/build.sh
- examples/using_make/build.sh
Verifies that the different build and install alternatives works.
Lowering the minimum CMake requirement for the examples to match the
library (v3.11) and change some parts due to its lack of functionality.
> Build the build examples in CI

- .github/workflows/ci.yml
- README.md
- adapters/libev.h
- tests/CMakeLists.txt
- tests/ct_async_libev.c
- tests/ct_async_libuv.c
Add adapter and test for using the event library `libev` for the asynchronous API
- Closes #48
- Found an issue in hiredis adapter impl. regarding unused parameters which will be addressed, but temporary fixed in the test binary.
Added a similar test for already handled `libuv`
> Add libev adapter and tests for event libraries libev and libuv

- hircluster.c
- hircluster.h
- tests/ct_connection.c
Add API to configure a username that will be used during authentication:
`int redisClusterSetOptionUsername(redisClusterContext *cc, const char *username)`
When a username and password is configured an `AUTH <username> <password>` is sent
after a connection is established to a cluster node.
If only password is configured an `AUTH <password>` is sent instead.
Fixes #42
> Support AUTH with username

- README.md
- hircluster.c
Hi,
In our use case we have a stateful Luajit wrapper for this driver, requiring us to reset the wrapper status each time (to avoid being stuck in pipeline mode without resetting the driver status between requests).
When we called that function, we also called redisResetCluster() - which causes a complete connection reset if not used after a pipeline.
Added a suggested PR to documentation to avoid future confusion in usage.
Thanks
> Improve redisClusterReset documentation.

- hiutil.c
Remove conditional code with empty body that was being
used to avoid an unused-parameter compiler warning for
the case where HI_HAVE_BACKTRACE is not set.
The (void) pattern used here is a common alternative -
it avoids the warning, makes for slightly cleaner code
and removes the empty blocks that lgtm is recommending
against.
> ci: resolve final lgtm.com recommendations

- hircluster.c
Analogue to redisClusterAsyncFormattedCommand, where the acc and acc->cc
errors are reset before sending the request.
Reason: The redisClusterAsyncCallback callback checks acc->err and omits the
reply if it is set.
> reset cluster context errors in redisClusterAsyncFormattedCommandToNode

- tests/CMakeLists.txt
- tests/clusterclient_reconnect_async.c
- tests/scripts/reconnect-test.sh
as promised last week, this new test examines
* redisClusterAsyncCommandToNode
* reconnects
* functionality without cluster mode enabled. this is handy for applications wanting to support both cluster and standalone mode, and don't want all their reply callbacks in two forms (`redisClusterAsyncContext` for cluster and `redisAsyncContext` for standalone) :)
The `clusterclient_reconnect_async.c` is quite similar to the `clusterclient_async.c`, except it sends the next command after receiving a reply from the previous command. It also works for standalone Redis nodes (without cluster mode), and uses the redisClusterAsyncCommandToNode function to send the command to the first node. If it receives any I/O error, the program performs a reconnect.
Naming is hard though and I'm open to any …
> tests: add reconnect test

- .github/workflows/ci.yml
- CMakeLists.txt
- command.c
- hircluster.c
- hiredis_cluster.def
- hiutil.c
- hiutil.h
- tests/CMakeLists.txt
- tests/clusterclient.c
- tests/clusterclient_all_nodes.c
- tests/ct_commands.c
- tests/ct_connection_ipv6.c
- tests/ct_out_of_memory_handling.c
- win32.h
Adding Windows and macOS builds to CI to verify that hiredis-cluster supports the same platforms as hiredis.
Building on Windows required corrections in the exported functions file (.def) and multiple include directive changes.
For macOS an include path was missing and linkage was corrected.
Fixes #72
> Add windows and macOS builds to CI

- hircluster.c
- hircluster.h
The flag REDIS_BLOCK is not used for anything in `hiredis-cluster`
and is a leftover from `hiredis` (where it is used).
Deprecating APIs which have no effect or can be replaced:
-  int redisClusterSetOptionConnectBlock(redisClusterContext *cc);
-  int redisClusterSetOptionConnectNonBlock(redisClusterContext *cc)
-  redisClusterContext *redisClusterConnectNonBlock(const char *addrs, int flags);
This API uses `cluster_update_route()` which is blocking anyway, i.e waits for `AUTH` and `CLUSTER SLOTS` responses.
There are no difference to `hiredis-vip` regarding this behavior.
> Deprecate non-block options which have no effect

- tests/ct_commands.c
- tests/ct_specific_nodes.c
Add tests to verify that MULTI currently requires to be sent to a specific node and works using the async node specific API.
> Add asynchronous transaction tests

- .github/workflows/redis_compability.yml
- hircluster.c
- tests/CMakeLists.txt
- tests/ct_commands.c
- tests/ct_connection.c
- tests/ct_specific_nodes.c
- tests/scripts/redis-cluster
- tests/test_utils.c
- tests/test_utils.h
Run all tests on different Redis versions by setting up the cluster using containers.
Currently version `5.0.14`, `6.0.16`, `6.2.7` and `7.0.0` are tested,
but adding a new version is simple due to that official Redis containers are used.
Versions 5.0 and 6.0 required some test-cases to be skipped, due to used commands were added more recently.
Version 7.0 required a correction while parsing `CLUSTER SLOTS` and additional configuration.
While running tests an intermittent issue regarding `DEBUG SLEEP` was found and fixed.
> Add Redis compatibility testing to CI

- hircluster.c
Remove use of:
REDIS_BLOCK
REDIS_CONNECTED
initially added by `hiredis-vip` due to its non-block socket use, which later was changed.
> Remove usage of hiredis internal flags

- CMakeLists.txt
- Makefile
- examples/using_cmake_externalproject/CMakeLists.txt
- examples/using_cmake_separate/build.sh
- examples/using_make/build.sh
* Use pedantic warnings for examples.
* Use c99 when building the examples too.
* Update hiredis version in the build examples.
* Build warnings are now equal in both Make and CMake builds.
> Build examples updates

- CMakeLists.txt
- Makefile
- hircluster.c
- tests/ct_out_of_memory_handling.c
Connect using redisConnectWithOptions() to set timeout values at the same time.
This requires disabling `missing-field-initializers` warnings, which match how its done in `redis` and `hiredis`.
> Connect refactoring

- hircluster.c
- tests/ct_commands.c
- tests/ct_pipeline.c
There is no reason to retry a request when it contains multiple keys that don't belong to the same hash slot.
> No command retries due to CROSSSLOT

- hircluster.c
- tests/CMakeLists.txt
This PR fixes 3 async issues:
1. When a node is removed all registered command callbacks are called with a NULL response.
This can happen when a new cluster topology is fetched. During this command callback handling
a NULL response might trigger the use of the nodes dict that is currently under deletion, which triggers a crash.
By making sure the nodes dict is replaced before we delete the old one a crash is avoided.
2. Return an error instead of asserting when a user attempts to send a command while a connection is disconnecting.
3. Correcting possible memory issue during MOVED handling.
Fixes #105
> Fix problems during async node disconnects

- hiutil.c
- hiutil.h
- win32.h
When using MinGW64 compilers these minor changes are needed to resolve build warnings and errors.
> Updates to resolve build issues on Windows platforms

- .github/workflows/ci.yml
- tests/CMakeLists.txt
~~Note:
Tests are not built due to some version mismatch in libevent.
`vcpkg install --triplet x64-windows libevent` that works for the windows job seems to give different libevent headers when building with MinGW.~~
> Build using MinGW64 in CI

- hircluster.c
- tests/CMakeLists.txt
- tests/clusterclient_async_sequence.c
- tests/scripts/timeout-handling-test.sh
When a context is freed all its callbacks are called with a NULL response.
During the callback handling there is an attempt to update the topology after a number of attempts.
If the node is removed during this topology change the context's pointer to the node will be cleared.
The callbacks that follows needs to be able to finish, i.e not asserting.
Added a testcase that can trigger the issue.
Since the [Redis config `cluster-node-timeout`](https://github.com/redis/redis/blob/ce4ebe6ba858bd6be7cabdc830f5ef30d6fcd37a/src/config.c#L3118) allows a 0 value this is also accepted (and used in the testcase).
Fixes #111
> No assert in the callback handling when a node is already removed

- .github/workflows/ci.yml
- CMakeLists.txt
- tests/scripts/timeout-handling-test.sh
Installing hiredis as an own step in CI to avoid issues with CMake < v1.20 and its FetchContent functionality.
> Lift hiredis to v1.1.0 in CI and tests

- hircluster.c
- tests/CMakeLists.txt
- tests/clusterclient_async.c
- tests/scripts/connect-error-using-cluster-nodes-test.sh
When fetching the cluster topology using the default command `CLUSTER NODES` from a node without any knowledge of the cluster, i.e. no slot information, there is an assert in the `hiarray_sort` function.
Lets return an error and error-string so that the next known node can be queried instead.
> Fix crash when using "CLUSTER NODES"

- hircluster.c
- tests/scripts/ask-redirect-test.sh
Use correct part of the ASK response string as key when
adding the new cluster node to the internal nodes dict.
The new node can now be found during handling of ASK responses
instead of getting an erroneous `Out of memory` error.
> Handle multiple ASK redirect command responses

- hircluster.c
- hircluster.h
- tests/ct_out_of_memory_handling.c
`cc->slots` contains a sorted array of slot-ranges, but is not used internally nor provided via the public interface.
The same information can be extracted via the nodes dict  `cc->nodes`.
This PR removes the array.
The move of the slot-range check is covered by the existing test `connect-error-using-cluster-nodes-test.sh`
> Remove unused cluster_slots array 

- hircluster.c
- tests/CMakeLists.txt
- tests/clusterclient_async_sequence.c
- tests/scripts/command-from-callback-test.sh
When nodes are removed their outstanding requests are "cancelled" by giving a NULL reply to their callbacks.
If a user resends a command from this callback the slot-to-node information (`cc->table`) might be wrong,
pointing to a removed `cluster_node`.
Changing the order of removal fixes the problem, indicated by the added testcase.
Fixes #124
> Fix issue of sending commands from reply callback

- hircluster.c
- tests/CMakeLists.txt
- tests/clusterclient_async_sequence.c
- tests/scripts/ask-redirect-connection-error-test.sh
Propagate the connection timeout config to asynchronously connected nodes.
The command timeout change is covered by the existing test `timeout-handling-test`.
Very likely root cause of #119
> Fix the async connection timeout

- CMakeLists.txt
`hiredis-cluster` can download its dependency `hiredis` automatically.
The downloading of hiredis `v1.1.0` requires CMake v3.20 or later, which includes a correction in its FetchContent functionality.
Give some hints how to proceeded when using a older CMake instead of just failing.
This was mentioned in #121.
> Give build error message when using old CMake

- .github/workflows/ci.yml
- CMakeLists.txt
- examples/using_cmake_and_make_mixed/build.sh
The CMake build attempts to find the installed CMake packages for `hiredis`,
which are only installed if `hiredis` was built and installed using CMake.
By adding an alternative search for the library files we now handle setups
where `hiredis` was installed using its regular makefile.
Added a build example for verification.
> Find hiredis libraries when its CMake packages are not found during builds

- tests/ut_parse_cmd.c
Attempt to silence Coverity Scan (false) warning.
`c->clen` is uint32_t while redisFormatCommand returns int; -1 on error, which becomes 0xFFFFFFFF in uint32_t.
> Check redisFormatCommand error result in test suite

- .github/workflows/ci.yml
- .github/workflows/coverity.yml
- .github/workflows/redis_compability.yml
There are sometimes problems with accessing apt repositories from CI,
which results in failing CI runs.
By caching the packages using:
https://github.com/marketplace/actions/cache-apt-packages
we should get more stable (and faster) CI runs.
> Use cached apt packages in CI

- command.c
- hircluster.c
- tests/ct_async.c
- tests/ct_commands.c
- tests/ct_connection.c
- tests/ct_connection_ipv6.c
- tests/ct_out_of_memory_handling.c
- tests/ct_pipeline.c
- tests/ct_specific_nodes.c
- tests/ut_parse_cmd.c
The diagnostics in Clang 15 is stricter and found a lot of:
```
[-Werror,-Wstrict-prototypes]
function declaration without a prototype is deprecated
```
> Fix builds when using Clang 15

- README.md
- hircluster.c
- hircluster.h
- tests/clusterclient_all_nodes.c
- tests/clusterclient_reconnect_async.c
- tests/ct_connection.c
- tests/ct_out_of_memory_handling.c
- tests/ct_specific_nodes.c
- tests/scripts/ask-redirect-test.sh
- tests/test_utils.c
The new name uses a prefix which match other exported types from the library.
A `cluster_node` typedef is kept for backwards compatibility.
This includes changes of the types internal create and "deinit" functions,
and renaming them to:
- createRedisClusterNode()
- freeRedisClusterNode()
> Rename type `cluster_node` to `redisClusterNode`

- .github/workflows/ci.yml
The Ubuntu 18.04 Actions runner image is deprecated and will be removed by 1 April 2023.
- Remove builds with gcc-4, gcc-5, gcc-6, clang-3.9 which are not directly available in apt for Ubuntu 20.04.
- Lift default used compilers to gcc-10 and clang-12 (matching default in 20.04)
> Replace deprecated ubuntu-18.04 in CI

- CMakeLists.txt
The version file for the CMake package enables users to ask for a specific version like:
` find_package(hiredis_cluster 0.10.1 REQUIRED)`    
which will find and accept all `0.10.x` versions but not `0.11.0`  (using [CMakePackageConfigHelpers](https://cmake.org/cmake/help/v3.11/module/CMakePackageConfigHelpers.html#generating-a-package-version-file)).
Additionally, this PR fixes a problem that CMake's `find_package()` don't understand which version that is used when the build downloads the hiredis package using `FetchContent`. This is fixed by creating a version file stub containing the package version.
This fixes a problem seen in PR #150, a testcase that should be run when using hiredis 1.0.1 will not run even when the build downloads hiredis 1.0.1.
> Create and install a version file for the hiredis-cluster CMake package

- .github/workflows/ci.yml
- tests/CMakeLists.txt
- tests/scripts/redirect-with-hostname-test.sh
The async testcase is run depending on used hiredis version due to https://github.com/redis/hiredis/issues/1171.
CI is updated to a pre-v1.1.1 version of hiredis to make sure we run the added testcase,
but local builds will keep its old behavior.
> Add test of redirects with hostname

- README.md
- examples/using_make/build.sh
- hircluster.c
- Define `_XOPEN_SOURCE` where needed instead of require it to be defined when building using Make.
- Update the `### Alternative build using Makefile directly` section in the README how `hiredis` is found.
> Improve Make builds and its README section

- README.md
- hircluster.c
- hircluster.h
- hiredis_cluster.def
- tests/ct_connection.c
A connect callback is more flexible than providing connection options using the options API. The user can apply connection specific options (such as socket options) from the connect callback.
Additional small changes:
* Don't set command timeout after redisReconnect, because hiredis does this automatically. This saves a few syscalls at reconnect.
* Improve documentation of async connect in README. Some of this info seems to have been copied from hiredis, so it wasn't even correct for hiredis-cluster.
> Add connect callback for the sync API

- hircluster.c
- hiredis_cluster.def
- tests/CMakeLists.txt
- tests/ct_out_of_memory_handling.c
- tests/scripts/redirect-with-ipv6-test.sh
- tests/scripts/simulated-redis.pl
When parsing the endpoint in an ASK redirect response the last occurance of the port separator `:`
needs to be looked for since IPv6 addresses can contain this character.
Previously the first was used which gives parse errors.
This PR includes a test to trigger the fault and to verify the correction.
This includes an added option `--ipv6` to simulated-redis.pl to be able to start a IPv6 server.
> Correct parsing of an IPv6 address in an ASK redirect

- .github/workflows/ci.yml
- .github/workflows/redis_compability.yml
- tests/CMakeLists.txt
- tests/scripts/redirect-with-ipv6-test.sh
Since Github runners seems to work fine with IPv6 lets enable these tests in CI.
Includes a fix for testcase `redirect-with-ipv6` due to the new redirect behavior
and a fix to show the testcase `ct_connection_ipv6` as disabled when IPv6 is disabled.
> Enable IPv6 tests in CI

- README.md
- hircluster.c
- hircluster.h
- hiredis_cluster.def
- tests/ct_connection.c
- tests/ct_out_of_memory_handling.c
- tests/ct_specific_nodes.c
- tests/test_utils.c
Rename node iterator type and its functions:
`nodeIterator`         to `redisClusterNodeIterator`
`initNodeIterator(..)` to `redisClusterInitNodeIterator(..)`
`nodeNext(..)`         to  `redisClusterNodeNext(..)`
Renaming of:
`cluster_update_route` to `redisClusterUpdateSlotMap()`
Old names are still defined for backward compability,
but `HIRCLUSTER_NO_OLD_NAMES` can be defined when backward compability with old types or function names is not needed.
> Prefix some API functions and types correctly

- README.md
- hircluster.c
- hircluster.h
- hiredis_cluster.def
- tests/ct_async.c
Adds a new public function `redisClusterAsyncConnect2()` which uses the attached event engine to get the initial slot map asynchronously compared to the legacy function `redisClusterAsyncConnect()` which is a blocking call.
Closes #123
> Add redisClusterAsyncConnect2()

- tests/CMakeLists.txt
- tests/scripts/cluster-scale-down-test.sh
The new testcase covers the new behaviour of updating slotmap due to error in sync API (#182).
Adapted from #87.
> Add cluster scale down test

- command.c
- tests/ut_parse_cmd.c
The code for finding keys in XREAD and XREADGROUP commands was untested and incorrect. Here it is fixed and a test case is added.
Fixes #186
> Fix code for XREAD and XREADGROUP and add test case

- tests/scripts/cluster-scale-down-test.sh
- tests/scripts/dbsize-to-all-nodes-during-scaledown-test-async.sh
- tests/scripts/dbsize-to-all-nodes-during-scaledown-test.sh
- tests/scripts/simulated-redis.pl
- Terminate a clusterclient directly instead of first closing its client socket.
This avoids that hiredis-cluster might succeed to reconnect to the server before the server has shutdown.
- Close the simulated-redis's listener socket early improves stability.
- Add check for alternative output from clusterclient in testcase `cluster-scale-down-test.sh`, `dbsize-to-all-nodes-during-scaledown-test.sh`and `dbsize-to-all-nodes-during-scaledown-test-async.sh`, which depends on timing.
> Fix timing issues in flaky scaledown tests

- hircluster.c
- tests/CMakeLists.txt
- tests/clusterclient_async.c
- tests/ct_connection.c
- tests/scripts/slots-not-served-test-async.sh
- tests/scripts/slots-not-served-test.sh
The sync-API will now update the slotmap before attempting to send a command when the slot is not served.
The async-API will initate the slotmap update in parallell so that the next command might have an updated slotmap.
This also fix an additional issue by using the correct function name for `redisClusterUpdateSlotmap()`.
The former name `cluster_update_route()` is not defined when `HIRCLUSTER_NO_OLD_NAMES` is defined, which would break the build.
Fixes #191
> Update slotmap when slot is not served by any node

- hircluster.c
The current implementation assumes that the entire part is only 2 characters when the IP and port are not set (IP is empty and port is 0). However, this is incorrect because the '@cport' is also present so the current check fails. Additionally, there may be an optional ',hostname' as well which is not accounted for.
The fix here simply changes the logic from "if the part is ':0'" to "if the part starts with ':0'".
> Fix the check for ":0@0" in CLUSTER NODES result

- hircluster.c
Don't skip calling redisAsyncDisconnect(context) on contexts with errors.
This makes sure that all pending request callbacks are invoked with a NULL reply, not only on contexts without errors.
Attempted to add a testcase covering this scenario, but could not reproduce it using simulated-redis tests.
Fixes #203
> Invoke all callbacks during redisClusterAsyncDisconnect()

- command.c
When building with the gcc -Wshadow option, a warning is generated in redis_parse_cmd() because the second and third declarations of the same-named kpos variable share scope.  It's benign but it'd be great to have clean compilation when using this option.
> Fix a compilation warning in command.c relating to kpos shadowing

- README.md
- examples/src/CMakeLists.txt
- examples/src/clientside_caching_async.c
- examples/using_cmake_separate/build.sh
- hircluster.c
- hircluster.h
- tests/ct_async.c
If `hiredis` >= v1.1.0 is used an alternative connect callback can be registered using:
```
int redisClusterAsyncSetConnectCallbackNC(redisClusterAsyncContext *acc,
redisConnectCallbackNC *fn);
```
The callback function should have the following prototype, aliased to `redisConnectCallbackNC`:
`void(redisAsyncContext *ac, int status);`
The connect callback will be passed a non-const `redisAsyncContext*` on invocation which
e.g. allows the callback to set a push callback.
The build will check if the used hiredis version supports it, but the new API can also manually be disabled in a build via:
`CFLAGS=-DHIRCLUSTER_NO_NONCONST_CONNECT_CB`
**Note:** Not available on Windows. The file `hiredis_cluster.def` would need to include `redisClusterAsyncSetConnectCallbackNC` only when `hiredis` >= …
> Add non-const connect callback

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/coverity.yml
- .github/workflows/redis_compability.yml
Pin the Github Action dependencies to the hash according to secure software development best practices
recommended by the Open Source Security Foundation (OpenSSF).
When developing a CI workflow, it's common to version-pin dependencies (i.e. actions/checkout@v4). However, version tags are mutable, so a malicious attacker could overwrite a version tag to point to a malicious or vulnerable commit instead.
Pinning workflow dependencies by hash ensures the dependency is immutable and its behavior is guaranteed.
This PR also adds a [dependabot](https://docs.github.com/en/code-security/dependabot) which will perform weekly checks of the Github actions used in CI.
When a newer version is found a pull request is opened to suggest a lift.
Recommendation details: …
> Pin Github action versions in CI and add dependabot for automated updates 

- .github/workflows/ci.yml
- .github/workflows/coverity.yml
- .github/workflows/redis_compability.yml
This sets the default permission for CI workflows to only be able to read from the repository (scope: "contents").
A compromised action will not be able to modify the repo or even steal secrets since all other permission-scopes are implicit set to "none", i.e. not permitted.
More about permissions and scope can be found here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
> Set read-only permission for Github Actions in CI

- .github/workflows/ci.yml
Install the missing vcpkg `pkgconf` since it's not longer preinstalled in runner `windows-latest`.
> Fix build issue in CI for Windows

- .github/workflows/ci.yml
- examples/src/example_async.c
- examples/using_cmake_and_make_mixed/build.sh
- examples/using_cmake_externalproject/CMakeLists.txt
- examples/using_cmake_separate/build.sh
- examples/using_make/build.sh
APT packages are sometimes removed so lets use the Github Action [aminya/setup-cpp](https://github.com/aminya/setup-cpp) to setup the compiler,
which fixes current CI issues with missing compiler. This action will also install the requested CMake version.
This PR includes the following changes:
- Use latest GCC, Clang and CMake in CI
- Fix warnings in examples
> Setup compiler and CMake in CI using a new Github Action

- hircluster.c
- hircluster.h
Closes #230.
I did not add new tests as original redisClusterv* APIs are not tested directly, and test coverage should not change. Please comment in this PR if separate specialized tests are required.
The only disadvantage of this PR that I see, is that va_start() is called in more cases. It can add some (albeit minuscule) overhead, but all such cases end in an error anyway.
> Add redisClustervCommandToNode and redisClustervAppendCommandToNode to library API

- tests/clusterclient_async.c
- tests/clusterclient_reconnect_async.c
Use the correct libevent2 type `evutil_socket_t` instead of `int` when implementing the libevent2 callback function in our tests. On Windows `evutil_socket_t` is a `intptr_t` (long long int) and this fixes the build errors for gcc-14 on Windows/MinGW.
[Defined in include/event2/event.h:](http://www.wangafu.net/~nickm/libevent-2.0/doxygen/html/event_8h.html)
typedef void(* 	event_callback_fn )(evutil_socket_t, short, void *)
> Use correct signature for `event_callback_fn` (libevent2) in tests

- hircluster.c
- hircluster.h
- tests/CMakeLists.txt
- tests/clusterclient_async.c
- tests/scripts/client-disconnect-test.sh
- tests/scripts/client-disconnect-without-slotmap-update-test.sh
- No slot map updates during a client shutdown.
- Don't follow redirects when a shutdown is requested to avoid reconnects or adding new nodes.
- Don't accept new commands when the client is about to shutdown.
Fixes #222 and #219
> Don't initiate new connections during a client shutdown (async API)

- hircluster.c
When hiredis API `redisAsyncFormattedCommand()` fail to push a given callback to its internal queue we need to free the memory of `cluster_async_data` (which is used as `privdata`).
Before #225 this could happen when sending a command right after initiating a disconnect, but now its mainly in OOM cases.
Make sure we also keep the error message from `redisAsyncFormattedCommand()`.
Fixes #229
> Free `cluster_async_data` in cases where hiredis don't takes ownership

- .github/dependabot.yml
Use the grouping feature in `dependabot` to bundle multiple updates into a single PR during the weekly check.
> dependabot: bundle multiple dependency updates in one PR

- .github/workflows/ci.yml
- .github/workflows/db-compatibility.yml
- CMakeLists.txt
- examples/using_cmake_and_make_mixed/build.sh
- examples/using_cmake_externalproject/CMakeLists.txt
- examples/using_cmake_separate/build.sh
- examples/using_make/build.sh
- Use latest release of hiredis (v1.3.0)
This release of hiredis includes a CMakeLists.txt fix to support CMake 4.0.
Fixes CI issues when Github runners have CMake 4.0.
Additional CI fixes:
- Use latest clang and CMake in CI
- Add Valkey 8.1 to compatibility test in CI  
Update versions of each Valkey-branch that is tested.
- Remove prepare step in macOS CI since ninja already installed
> Use latest hiredis v1.3.0 as default
